SELECT 'PROD' AS Environment,
	   U.DISPLAY_NAME AS UserAccount,
	   L.NUM_OF_FULL_CONCURRENT_USERS NUM_OF_FULL_CONCURRENT_USERS, 
	   L.LOGIN_DATE AS 'LoginDate (GMT)',
	   DATEADD(HOUR, -4, L.LOGIN_DATE) AS 'LoginDate (EST)',
	   LP.HIERARCHICAL_NAME PrimaryLocation,
	   LANG.DISPLAY_NAME AS Locale
FROM Prod.DATACENTER.LOGIN_TRACKER L
JOIN Prod.ENGINE.USER_SETTINGS U ON (L.USER_ID = U.USER_ID)
LEFT JOIN Prod.DATACENTER.LOCATION_PROFILE LP ON (L.USER_LOCATION_ID = LP.LOCATION_PROFILE_ID)
LEFT JOIN Prod.DATACENTER.TIME_ZONES TZ ON U.TIME_ZONE_ID=TZ.TIME_ZONE_ID
LEFT JOIN Prod.DATACENTER.LOCALES LANG ON U.LOCALE_ID=LANG.LOCALE_ID
--WHERE L.LOGIN_DATE BETWEEN '03/28/2022' AND '03/31/2022'
UNION
SELECT 'TEST' AS Environment,
	   U.DISPLAY_NAME AS UserAccount,
	   L.NUM_OF_FULL_CONCURRENT_USERS NUM_OF_FULL_CONCURRENT_USERS, 
	   L.LOGIN_DATE LoginDate,
	   DATEADD(HOUR, -4, L.LOGIN_DATE),
	   LP.HIERARCHICAL_NAME PrimaryLocation,
	   LANG.DISPLAY_NAME AS Locale
FROM Test.DATACENTER.LOGIN_TRACKER L
JOIN Test.ENGINE.USER_SETTINGS U ON (L.USER_ID = U.USER_ID)
LEFT JOIN Test.DATACENTER.LOCATION_PROFILE LP ON (L.USER_LOCATION_ID = LP.LOCATION_PROFILE_ID)
LEFT JOIN Test.DATACENTER.TIME_ZONES TZ ON U.TIME_ZONE_ID=TZ.TIME_ZONE_ID
LEFT JOIN Test.DATACENTER.LOCALES LANG ON U.LOCALE_ID=LANG.LOCALE_ID
--WHERE L.LOGIN_DATE BETWEEN '03/28/2022' AND '03/31/2022'
UNION
SELECT 'DEV' AS Environment,
	   U.DISPLAY_NAME AS UserAccount,
	   L.NUM_OF_FULL_CONCURRENT_USERS NUM_OF_FULL_CONCURRENT_USERS, 
	   L.LOGIN_DATE LoginDate,
	   DATEADD(HOUR, -4, L.LOGIN_DATE),
	   LP.HIERARCHICAL_NAME PrimaryLocation,
	   LANG.DISPLAY_NAME AS Locale
FROM Dev.DATACENTER.LOGIN_TRACKER L
JOIN Dev.ENGINE.USER_SETTINGS U ON (L.USER_ID = U.USER_ID)
LEFT JOIN Dev.DATACENTER.LOCATION_PROFILE LP ON (L.USER_LOCATION_ID = LP.LOCATION_PROFILE_ID)
LEFT JOIN Dev.DATACENTER.TIME_ZONES TZ ON U.TIME_ZONE_ID=TZ.TIME_ZONE_ID
LEFT JOIN Dev.DATACENTER.LOCALES LANG ON U.LOCALE_ID=LANG.LOCALE_ID
--WHERE L.LOGIN_DATE BETWEEN '03/28/2022' AND '03/31/2022'
ORDER BY 5
