-- Returns list of user and group counts with the same display name
SELECT DISPLAY_NAME, COUNT(*) AS COUNT
FROM ENGINE.USER_SETTINGS
WHERE IS_DISABLED=0
  AND IS_INACTIVE=0
GROUP BY DISPLAY_NAME
HAVING COUNT(*)>1
ORDER BY 1

-- Returns active users and groups with the same display name
SELECT U.USER_NAME, U.DISPLAY_NAME, U.ETQ$CREATED_DATE, U2.DISPLAY_NAME AS CREATED_BY, U.ETQ$MODIFIED_DATE, U3.DISPLAY_NAME AS MODIFIED_BY, U.IS_GROUP
FROM ENGINE.USER_SETTINGS U
LEFT JOIN ENGINE.USER_SETTINGS U2 ON U.ETQ$AUTHOR=U2.USER_ID
LEFT JOIN ENGINE.USER_SETTINGS U3 ON U.ETQ$LAST_EDITOR=U3.USER_ID
WHERE U.DISPLAY_NAME IN (SELECT DISPLAY_NAME
							FROM ENGINE.USER_SETTINGS
							WHERE IS_DISABLED=0
							  AND IS_INACTIVE=0
							GROUP BY DISPLAY_NAME
							HAVING COUNT(*)>1)
ORDER BY DISPLAY_NAME, ETQ$CREATED_DATE
