SELECT FS.FIELD_ID,
	   FS.FIELD_NAME,
	   FS.DISPLAY_NAME,
	   FS.ETQ$CREATED_DATE,
	   FS.BASE_TABLE,
	   FS.LOOKUP_SQL_QUERY,
	   FS.BASE_TABLE_PK,
	   FS.LOOKUP_DISPLAY_VALUE,
	   FS.KEYWORD_FORMULA,
	   FS.TABLE_FIELD_NAME
FROM ENGINE.FIELD_SETTINGS FS
WHERE FS.LOOKUP_SQL_QUERY IS NOT NULL
  AND BASE_TABLE LIKE '%TABLE_NAME%'
  and DISPLAY_NAME like '%FieldDisplay%'
