DECLARE @SearchFor NVARCHAR(100)
SET @SearchFor = 'Text you want to search for'
SET @SearchFor = '%' + @SearchFor + '%'

-- Form Layout JSON
SELECT 'FORM_SETTINGS' AS SettingObject, 'Form Layout' AS SettingType,
		FS.FORM_ID AS ID, FS.FORM_NAME AS SettingName, FS.DISPLAY_NAME AS DISPLAY_NAME, CAST(FS.ON_OPEN_FORMULA AS NVARCHAR(MAX))AS EtQScript
FROM ENGINE.FORM_SETTINGS FS
WHERE FS.FORM_LAYOUT LIKE @SearchFor
UNION
-- Form On-Open EtQScript
SELECT 'FORM_SETTINGS' AS SettingObject, 'On Open' AS SettingType,
		FS.FORM_ID AS ID, FS.FORM_NAME AS SettingName, FS.DISPLAY_NAME AS DISPLAY_NAME, CAST(FS.ON_OPEN_FORMULA AS NVARCHAR(MAX))AS EtQScript
FROM ENGINE.FORM_SETTINGS FS
WHERE FS.ON_OPEN_FORMULA LIKE @SearchFor
UNION
-- Form On-Save EtQScript
SELECT 'FORM_SETTINGS' AS SettingObject, 'On Save' AS SettingType,
		FS.FORM_ID, FS.FORM_NAME, FS.DISPLAY_NAME, CAST(FS.ON_BEFORE_SAVE_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.FORM_SETTINGS FS
WHERE FS.ON_BEFORE_SAVE_FORMULA LIKE @SearchFor
UNION
-- Form On-Refresh EtQScript
SELECT 'FORM_SETTINGS' AS SettingObject, 'On Refresh' AS SettingType,
		FS.FORM_ID, FS.FORM_NAME, FS.DISPLAY_NAME, CAST(FS.ON_AFTER_REFRESH_FORMULA AS NVARCHAR(MAX))
		E
FROM ENGINE.FORM_SETTINGS FS
WHERE FS.ON_AFTER_REFRESH_FORMULA LIKE @SearchFor
UNION
-- Link Description EtQScript
SELECT 'FORM_SETTINGS' AS SettingObject, 'Link Description' AS SettingType,
		FS.FORM_ID, FS.FORM_NAME, FS.DISPLAY_NAME, CAST(FS.LINK_DESCRIPTION_ETQSCRIPT AS NVARCHAR(MAX))
FROM ENGINE.FORM_SETTINGS FS
WHERE FS.LINK_DESCRIPTION_ETQSCRIPT LIKE @SearchFor
UNION
-- Form Notification Email Subject EtQScript
SELECT 'FORM_SETTINGS' AS SettingObject, 'Notification Subject' AS SettingType,
		FS.FORM_ID, FS.FORM_NAME, FS.DISPLAY_NAME, CAST(FS.NOTIFICATION_SUBJECT AS NVARCHAR(MAX))
FROM ENGINE.FORM_SETTINGS FS
WHERE FS.NOTIFICATION_SUBJECT LIKE @SearchFor
UNION
-- Form Notification Email Body EtQScript
SELECT 'FORM_SETTINGS' AS SettingObject, 'Notification Body' AS SettingType,
		FS.FORM_ID, FS.FORM_NAME, FS.DISPLAY_NAME, CAST(FS.NOTIFICATION_BODY AS NVARCHAR(MAX))
FROM ENGINE.FORM_SETTINGS FS
WHERE FS.NOTIFICATION_BODY LIKE @SearchFor
UNION
-- Phase Assignment Email Subject EtQScript
SELECT 'PHASE_SETTINGS', 'Assignment Subject',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.ASSIGNMENT_SUBJECT AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.ASSIGNMENT_SUBJECT LIKE @SearchFor
UNION
-- Phase Assignment Email Body EtQScript
SELECT 'PHASE_SETTINGS', 'Assignment Body',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.ASSIGNMENT_BODY AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.ASSIGNMENT_BODY LIKE @SearchFor
UNION
-- Phase Notification Email Subject EtQScript
SELECT 'PHASE_SETTINGS', 'Notification Subject',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.NOTIFICATION_SUBJECT AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.NOTIFICATION_SUBJECT LIKE @SearchFor
UNION
-- Phase Notification Email Body EtQScript
SELECT 'PHASE_SETTINGS', 'Notification Body',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.NOTIFICATION_BODY AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.NOTIFICATION_BODY LIKE @SearchFor
UNION
-- Phase Assignment EtQScript
SELECT 'PHASE_SETTINGS', 'Assigned Formula',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.ASSIGNED_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.ASSIGNED_FORMULA LIKE @SearchFor
UNION
-- Phase Inbound Notification EtQScript
SELECT 'PHASE_SETTINGS', 'Inbound Notification Formula',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.INBOUND_NOTIFICATION_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.INBOUND_NOTIFICATION_FORMULA LIKE @SearchFor
UNION
-- Phase Outbound Notification EtQScript
SELECT 'PHASE_SETTINGS', 'Outbound Notification Formula',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.OUTBOUND_NOTIFICATION_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.OUTBOUND_NOTIFICATION_FORMULA LIKE @SearchFor
UNION
-- Forward Phase EtQScript
SELECT 'PHASE_SETTINGS', 'Forward Phases Formula',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.PHASES_FORWARD_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.PHASES_FORWARD_FORMULA LIKE @SearchFor
UNION
-- Backward Phase EtQScript
SELECT 'PHASE_SETTINGS', 'Backward Phases Formula',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.PHASES_BACKWARD_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.PHASES_BACKWARD_FORMULA LIKE @SearchFor
UNION
-- Special Forward Phase EtQScript
SELECT 'PHASE_SETTINGS', 'Special Phases Forward Formula',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.SPECIAL_FORWARD_PHASES_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.SPECIAL_FORWARD_PHASES_FORMULA LIKE @SearchFor
UNION
-- Who can use Special Phases EtQScript
SELECT 'PHASE_SETTINGS', 'Who can use Special Phases Forward Formula',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.WHO_CAN_USE_SPECIAL_FW_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.WHO_CAN_USE_SPECIAL_FW_FORMULA LIKE @SearchFor
UNION
-- Who can Void EtQScript
SELECT 'PHASE_SETTINGS', 'Who can void Formula',
		PS.PHASE_ID, PS.PHASE_NAME, PS.DISPLAY_NAME, CAST(PS.WHO_CAN_VOID_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.PHASE_SETTINGS PS
WHERE PS.WHO_CAN_VOID_FORMULA LIKE @SearchFor
UNION
-- Section Edit-When EtQScript
SELECT 'SECTION_SETTINGS', 'Edit Formula',
		SS.SECTION_ID, SS.SECTION_NAME, SS.DISPLAY_NAME, CAST(SS.EDIT_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.SECTION_SETTINGS SS
WHERE SS.EDIT_FORMULA LIKE @SearchFor
UNION
-- Section Read-Only When EtQScript
SELECT 'SECTION_SETTINGS', 'Read Formula',
		SS.SECTION_ID, SS.SECTION_NAME, SS.DISPLAY_NAME, CAST(SS.READ_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.SECTION_SETTINGS SS
WHERE SS.READ_FORMULA LIKE @SearchFor
UNION
-- Field Default EtQScript
SELECT 'FIELD_SETTINGS', 'Default Formula',
		FS.FIELD_ID, FS.FIELD_NAME, FS.DISPLAY_NAME, CAST(FS.DEFAULT_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.FIELD_SETTINGS FS
WHERE FS.DEFAULT_FORMULA LIKE @SearchFor
UNION
-- Field Translation EtQScript
SELECT 'FIELD_SETTINGS', 'Translation Formula',
		FS.FIELD_ID, FS.FIELD_NAME, FS.DISPLAY_NAME, CAST(FS.TRANSLATION_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.FIELD_SETTINGS FS
WHERE FS.TRANSLATION_FORMULA LIKE @SearchFor
UNION
-- Field Validation EtQScript
SELECT 'FIELD_SETTINGS', 'Validation Formula',
		FS.FIELD_ID, FS.FIELD_NAME, FS.DISPLAY_NAME, CAST(FS.VALIDATION_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.FIELD_SETTINGS FS
WHERE FS.VALIDATION_FORMULA LIKE @SearchFor
UNION
-- Field Keyword Formula
SELECT 'FIELD_SETTINGS', 'Keyword Formula',
		FS.FIELD_ID, FS.FIELD_NAME, FS.DISPLAY_NAME, CAST(FS.KEYWORD_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.FIELD_SETTINGS FS
WHERE FS.KEYWORD_FORMULA LIKE @SearchFor
UNION
-- Field On-Enter EtQScript
SELECT 'FIELD_SETTINGS', 'On Enter Formula',
		FS.FIELD_ID, FS.FIELD_NAME, FS.DISPLAY_NAME, CAST(FS.ON_ENTER AS NVARCHAR(MAX))
FROM ENGINE.FIELD_SETTINGS FS
WHERE FS.ON_ENTER LIKE @SearchFor
UNION
-- Field On-Change EtQScript
SELECT 'FIELD_SETTINGS', 'On Change Formula',
		FS.FIELD_ID, FS.FIELD_NAME, FS.DISPLAY_NAME, CAST(FS.ON_CHANGE AS NVARCHAR(MAX))
FROM ENGINE.FIELD_SETTINGS FS
WHERE FS.ON_CHANGE LIKE @SearchFor
UNION
-- Field On-Exit EtQScript
SELECT 'FIELD_SETTINGS', 'On Exit Formula',
		FS.FIELD_ID, FS.FIELD_NAME, FS.DISPLAY_NAME, CAST(FS.ON_EXIT AS NVARCHAR(MAX))
FROM ENGINE.FIELD_SETTINGS FS
WHERE FS.ON_EXIT LIKE @SearchFor
UNION
-- Field Lookup SQL Query
SELECT 'FIELD_SETTINGS', 'Lookup SQL Query',
		FS.FIELD_ID, FS.FIELD_NAME, FS.DISPLAY_NAME, CAST(FS.LOOKUP_SQL_QUERY AS NVARCHAR(MAX))
FROM ENGINE.FIELD_SETTINGS FS
WHERE FS.LOOKUP_SQL_QUERY LIKE @SearchFor
UNION
-- Data Source SQL query
SELECT 'DATASOURCE_SETTINGS', 'Statement',
		DS.DATASOURCE_ID, DS.DATASOURCE_NAME, DS.DISPLAY_NAME , CAST(DS.STATEMENT AS NVARCHAR(MAX))
FROM ENGINE.DATASOURCE_SETTINGS DS
WHERE DS.STATEMENT LIKE @SearchFor
UNION
-- EtQScript Profiles
SELECT 'ETQSCRIPT_PROFILES', 'Statement',
		SP.SCRIPT_PROFILE_ID, SP.DESIGN_NAME, SP.DISPLAY_NAME , CAST(SP.FORMULA AS NVARCHAR(MAX))
FROM DATACENTER.SCRIPT_PROFILE SP
WHERE SP.FORMULA LIKE @SearchFor
UNION
-- Task Profiles
SELECT 'TASK_PROFILES', 'Statement',
		TS.TASK_ID, TS.TASK_NAME, TS.DISPLAY_NAME , CAST(TS.EXECUTION_FORMULA AS NVARCHAR(MAX))
FROM ENGINE.TASK_SETTINGS TS
WHERE TS.EXECUTION_FORMULA LIKE @SearchFor
