SELECT APP.DISPLAY_NAME, WF.WORKFLOW_ID, WF.DISPLAY_NAME, PS.PHASE_ID, PS.DISPLAY_NAME, PS.PHASE_NAME, PI.ETQ$RECORD_ORDER
FROM ENGINE.WF_SETTINGS WF
JOIN ENGINE.FORM_SETTINGS FS ON WF.WORKFLOW_PARENT_FORM=FS.FORM_ID
JOIN ENGINE.APPLICATION_FORMS AF ON FS.FORM_ID=AF.FORM_ID
JOIN ENGINE.APPLICATION_SETTINGS APP ON AF.APPLICATION_ID=APP.APPLICATION_ID
JOIN ENGINE.WF_PHASE_INFO PI ON WF.WORKFLOW_ID=PI.WORKFLOW_ID
JOIN ENGINE.PHASE_SETTINGS PS ON PI.PHASE_ID=PS.PHASE_ID
WHERE WF.DISPLAY_NAME LIKE '%Workflow Name%'
  AND APP.DISPLAY_NAME='Document Control'
ORDER BY APP.DISPLAY_NAME, WF.DISPLAY_NAME, PI.ETQ$RECORD_ORDER
